Map<String, String> districtCodes = {

// Andaman and Nicobar (AN) - 3
  "Nicobar":"NI",
  "North and Middle Andaman":"NA",
  "South Andaman":"SA",

// Andhra Pradesh (AP) - 13
  "Anantapur":"AN",
  "Chittoor":"CH",
  "East Godavari":"EG",
  "Guntur":"GU",
  "YSR Kadapa":"CU",
  "Krishna":"KR",
  "Kurnool":"KU",
  "Prakasam":"PR",
  "Sri Potti Sriramulu Nellore":"NE",
  "Srikakulam":"SR",
  "Visakhapatnam":"VS",
  "Vizianagaram":"VZ",
  "West Godavari":"WG",

// Arunachal Pradesh (AR) - 25
  "Anjaw":"AJ",
  "Changlang":"CH",
  "Dibang Valley":"DVV",
  "East Kameng":"EK",
  "East Siang":"ES",
  "Kamle":"KML",
  "Kra Daadi":"KD",
  "Kurung Kumey":"KK",
  "Lepa-Rada":"LR",
  "Lohit":"EL",
  "Longding":"LD",
  "Lower Dibang Valley":"DV",
  "Lower Siang":"LS",
  "Lower Subansiri":"LB",
  "Namsai":"NM",
  "Pakke-Kessang":"PK",
  "Papum Pare":"PA",
  "Shi-Yomi":"SY",
  "Siang":"SI",
  "Tawang":"TA",
  "Tirap":"TI",
  "Upper Siang":"US",
  "Upper Subansiri":"UB",
  "West Kameng":"WK",
  "West Siang":"WS",

// Assam (AS) - 33
  "Baksa":"BK",
  "Barpeta":"BP",
  "Biswanath":"BS",
  "Bongaigaon":"BO",
  "Cachar":"CA",
  "Charaideo":"CD",
  "Chirang":"CH",
  "Darrang":"DR",
  "Dhemaji":"DM",
  "Dhubri":"DU",
  "Dibrugarh":"DI",
  "Dima Hasao":"NC",
  "Goalpara":"GP",
  "Golaghat":"GG",
  "Hailakandi":"HA",
  "Hojai":"HJ",
  "Jorhat":"JO",
  "Kamrup":"KU",
  "Kamrup Metropolitan":"KM",
  "Karbi Anglong":"KG",
  "Karimganj":"KR",
  "Kokrajhar":"	KJ",
  "Lakhimpur":"LA",
  "Majuli":"MJ",
  "Morigaon":"MA",
  "Nagaon":"NN",
  "Nalbari":"NB",
  "Sivasagar":"ST",
  "Sonitpur":"SO",
  "South Salmara-Mankachar":"SM",
  "Tinsukia":"TI",
  "Udalguri":"UD",
  "West Karbi Anglong":"WK",

// Bihar (BR) - 38
  "Araria":"AR",
  "Arwal":"ARR",
  "Aurangabad":"AU",
  "Banka":"BA",
  "Begusarai":"BE",
  "Bhagalpur":"BG",
  "Bhojpur":"BJ",
  "Buxar":"BU",
  "Darbhanga":"DA",
  "East Champaran":"EC",
  "Gaya":"GA",
  "Gopalganj":"GO",
  "Jamui":"JA",
  "Jehanabad":"JE",
  "Kaimur":"KM",
  "Katihar":"KT",
  "Khagaria":"KH",
  "Kishanganj":"KI",
  "Lakhisarai":"LA",
  "Madhepura":"MP",
  "Madhubani":"MB",
  "Munger":"MG",
  "Muzaffarpur":"MZ",
  "Nalanda":"NL",
  "Nawada":"NW",
  "Patna":"PA",
  "Purnia":"PU",
  "Rohtas":"RO",
  "Saharsa":"SH",
  "Samastipur":"SM",
  "Saran":"SR",
  "Sheikhpura":"SP",
  "Sheohar":"SO",
  "Sitamarhi":"ST",
  "Siwan":"SW",
  "Supaul":"SU",
  "Vaishali":"VA",
  "West Champaran":"WC",

// Chandigarh (CH) - 1
  "Chandigarh":"CH",

// Chhattisgarh (CT) - 28
  "Balod":"BD",
  "Baloda Bazar":"BB",
  "Balrampur":"BR",
  "Bastar":"BA",
  "Bemetara":"BE",
  "Bijapur":"BJ",
  "Bilaspur":"BI",
  "Dantewada":"DA",
  "Dhamtari":"DH",
  "Durg":"DU",
  "Gariaband":"GB",
  "Gaurela-Pendra-Marwahi":"GPM",
  "Janjgir-Champa":"JC",
  "Jashpur":"JA",
  "Kabirdham":"KW",
  "Kanker":"KK",
  "Kondagaon":"KG",
  "Korba":"KB",
  "Koriya":"KJ",
  "Mahasamund":"MA",
  "Mungeli":"MG",
  "Narayanpur":"NR",
  "Raigarh":"RG",
  "Raipur":"RP",
  "Rajnandgaon":"RN",
  "Sukma":"SK",
  "Surajpur":"SJ",
  "Surguja":"SJJ",

// Dadra and Nagar Haveli and Daman and Diu (DD) - 3
  "Daman":"DA",
  "Diu":"DI",
  "Dadra and Nagar Haveli":"DN",

// National Capital Territory of Delhi (DL) - 11
  "Central Delhi":"CD",
  "East Delhi":"ED",
  "New Delhi":"ND",
  "North Delhi":"NO",
  "North East Delhi":"NE",
  "North West Delhi":"NW",
  "Shahdara":"SH",
  "South Delhi":"SD",
  "South East Delhi":"SED",
  "South West Delhi":"SW",
  "West Delhi":"WD",

// GOA (GA) - 2
  "North Goa":"NG",
  "South Goa":"SG",

// Gujarat (GJ) - 33
  "Ahmedabad":"AH",
  "Amreli":"AM",
  "Anand":"AN",
  "Aravalli":"AR",
  "Banaskantha":"BK",
  "Bharuch":"BR",
  "Bhavnagar":"BV",
  "Botad":"BT",
  "Chhota Udepur":"CU",
  "Dahod":"DA",
  "Dang":"DG",
  "Devbhoomi Dwarka":"DD",
  "Gandhinagar":"GA",
  "Gir Somnath":"GS",
  "Jamnagar":"JA",
  "Junagadh":"JU",
  "Kheda":"KH",
  "Kutch":"KA",
  "Mahisagar":"MH",
  "Mehsana":"MA",
  "Morbi":"MB",
  "Narmada":"NR",
  "Navsari":"NV",
  "Panchmahal":"PM",
  "Patan":"PA",
  "Porbandar":"PO",
  "Rajkot":"RA",
  "Sabarkantha":"SK",
  "Surat":"ST",
  "Surendranagar":"SN",
  "Tapi":"TA",
  "Vadodara":"VD",
  "Valsad":"VL",

// Haryana (HR) - 22
  "Ambala":"AM",
  "Bhiwani":"BH",
  "Charkhi Dadri":"CD",
  "Faridabad":"FR",
  "Fatehabad":"FT",
  "Gurgaon":"GU",
  "Hissar":"HI",
  "Jhajjar":"JH",
  "Jind":"JI",
  "Kaithal":"KT",
  "Karnal":"KR",
  "Kurukshetra":"KU",
  "Mahendragarh":"MA",
  "Nuh":"MW",
  "Palwal":"PW",
  "Panchkula":"PK",
  "Panipat":"PP",
  "Rewari":"RE",
  "Rohtak":"RO",
  "Sirsa":"SI",
  "Sonipat":"SNP",
  "Yamuna Nagar":"YN",

// Himachal Pradesh (HP) - 12
// "Bilaspur":"BI",
  "Chamba":"CH",
  "Hamirpur":"HA",
  "Kangra":"KA",
  "Kinnaur":"KI",
  "Kullu":"KULS",
  "Lahaul and Spiti":"LS",
  "Mandi":"MA",
  "Shimla":"SH",
  "Sirmaur":"SI",
  "Solan":"SO",
  "Una":"UN",

// Jammu and Kashmir (JK) - 20
  "Anantnag":"AN",
  "Bandipora":"BPR",
  "Baramulla":"BR",
  "Badgam":"BD",
  "Doda":"DO",
  "Ganderbal":"GB",
  "Jammu":"JA",
  "Kathua":"KT",
  "Kishtwar":"KW",
  "Kulgam":"KG",
  "Kupwara":"KU",
  "Poonch":"PO",
  "Pulwama":"PU",
  "Rajouri":"RA",
  "Ramban":"RB",
  "Reasi":"RS",
  "Samba":"SB",
  "Shopian":"SH",
  "Srinagar":"SR",
  "Udhampur":"UD",

// Jharkhand (JH) - 24
  "Bokaro":"BO",
  "Chatra":"CH",
  "Deoghar":"DE",
  "Dhanbad":"DH",
  "Dumka":"DU",
  "East Singhbhum":"ES",
  "Garhwa":"GA",
  "Giridih":"GI",
  "Godda":"GO",
  "Gumla":"GU",
  "Hazaribag":"HA",
  "Jamtara":"JA",
  "Khunti":"KH",
  "Koderma":"KO",
  "Latehar":"LA",
  "Lohardaga":"LO",
  "Pakur":"PK",
  "Palamu":"PL",
  "Ramgarh":"RM",
  "Ranchi":"RA",
  "Sahibganj":"SA",
  "Seraikela Kharsawan":"SK",
  "Simdega":"SI",
  "West Singhbhum":"WS",

// Karnataka (KA) - 30
  "Bagalkot":"BK",
  "Ballari":"BL",
  "Belgaum":"BG",
  "Bangalore Rural":"BR",
  "Bangalore Urban":"BN",
  "Bidar":"BD",
  "Chamarajnagar":"CJ",
  "Chikkaballapur":"CK",
  "Chikkamagaluru":"CKK",
  "Chitradurga":"CT",
  "Dakshina Kannada":"DK",
  "Davanagere":"DA",
  "Dharwad":"DH",
  "Gadag":"GA",
  "Gulbarga":"GU",
  "Hassan":"HS",
  "Haveri":"HV",
  "Kodagu":"KD",
  "Kolar":"KL",
  "Koppal":"KP",
  "Mandya":"MA",
  "Mysuru":"MY",
  "Raichur":"RA",
  "Ramanagara":"RM",
  "Shimoga":"SH",
  "Tumakuru":"TU",
  "Udupi":"UD",
  "Uttara Kannada":"UK",
  "Vijayapura":"BJ",
  "Yadgir":"YG ",

// Kerala (KL) - 14
  "Alappuzha":"AL",
  "Ernakulam":"ER",
  "Idukki":"ID",
  "Kannur":"KN",
  "Kasaragod":"KS",
  "Kollam":"KL",
  "Kottayam":"KT",
  "Kozhikode":"KZ",
  "Malappuram":"MA",
  "Palakkad":"PL",
  "Pathanamthitta":"PT",
  "Thrissur":"TS",
  "Thiruvananthapuram":"TV",
  "Wayanad":"WA",

// Lakshadweep (LD) - 1
  "Lakshadweep":"LD",

// Madhya Pradesh (MP) -55
  "Agar Malwa":"AG",
  "Alirajpur":"AL",
  "Anuppur":"AP",
  "Ashok Nagar":"AS",
  "Balaghat":"BL",
  "Barwani":"BR",
  "Betul":"BE",
  "Bhind":"BD",
  "Bhopal":"BP",
  "Burhanpur":"BU",
  "Chachaura-Binaganj":"CB",
  "Chhatarpur":"CT",
  "Chhindwara":"CN",
  "Damoh":"DM",
  "Datia":"DT",
  "Dewas":"DE",
  "Dhar":"DH",
  "Dindori":"DI",
  "Guna":"GU",
  "Gwalior":"GW",
  "Harda":"HA",
  "Hoshangabad":"HO",
  "Indore":"IN",
  "Jabalpur":"JA",
  "Jhabua":"JH",
  "Katni":"KA",
  "Khandwa":"EN",
  "Khargone":"WN",
  "Maihar":"MH",
  "Mandla":"ML",
  "Mandsaur":"MS",
  "Morena":"MO",
  "Narsinghpur":"NA",
  "Nagda":"NG",
  "Neemuch":"NE",
  "Niwari":"NI",
  "Panna":"PA",
  "Raisen":"RS",
  "Rajgarh":"RG",
  "Ratlam":"RL",
  "Rewa":"RE",
  "Sagar":"SG",
  "Satna":"ST",
  "Sehore":"SR",
  "Seoni":"SO",
  "Shahdol":"SH",
  "Shajapur":"SJ",
  "Sheopur":"SP",
  "Shivpuri":"SV",
  "Sidhi":"SI",
  "Singrauli":"SN",
  "Tikamgarh":"TI",
  "Ujjain":"UJ",
  "Umaria":"UM",
  "Vidisha":"VI",

// Maharashtra (MH) - 36
  "Ahmednagar":"AH",
  "Akola":"AK",
  "Amravati":"AM",
//  "Aurangabad":"AU",
  "Beed":"BI",
  "Bhandara":"BH",
  "Buldhana":"BU",
  "Chandrapur":"CH",
  "Dhule":"DH",
  "Gadchiroli":"GA",
  "Gondia":"GO",
  "Hingoli":"HI",
  "Jalgaon":"JG",
  "Jalna":"JN",
  "Kolhapur":"KO",
  "Latur":"LA",
  "Mumbai City":"MC",
  "Mumbai Suburban":"MU",
  "Nanded":"ND",
  "Nandurbar":"NB",
  "Nagpur":"NG",
  "Nashik":"NS",
  "Osmanabad":"OS",
  "Palghar":"PL",
  "Parbhani":"PA",
  "Pune":"PU",
  "Raigad":"RG",
  "Ratnagiri":"RT",
  "Sangli":"SN",
  "Satara":"ST",
  "Sindhudurg":"SI",
  "Solapur":"SO",
  "Thane":"TH",
  "Wardha":"WR",
  "Washim":"WS",
  "Yavatmal":"YA",

// Manipur (MN) - 16
  "Bishnupur":"BPR",
  "Chandel":"CDL",
  "Churachandpur":"CCpr",
  "Imphal East":"IE",
  "Imphal West":"IW",
  "Jiribam":"JBM",
  "Kakching":"KAK",
  "Kamjong":"KJ",
  "Kangpokpi":"KPI",
  "Noney":"NL",
  "Pherzawl":"PZ",
  "Senapati":"SE",
  "Tamenglong":"TML",
  "Tengnoupal":"TNL",
  "Thoubal":"TBL",
  "Ukhrul":"UKR",

// Meghalaya (ML) - 11
  "East Garo Hills":"EG",
  "East Khasi Hills":"EK",
  "East Jaintia Hills":"EJH",
  "North Garo Hills":"NGH",
  "Ri Bhoi":"RB",
  "South Garo Hills":"SG",
  "South West Garo Hills":"SWGH",
  "South West Khasi Hills":"SWKH",
  "West Jaintia Hills":"WG",
  "West Garo Hills":"WGG",
  "West Khasi Hills":"WK",

// Mizoram (MZ) - 11
  "Aizawl":"AI",
  "Champhai":"CH",
  "Hnahthial":"HH",
  "Khawzawl":"KZ",
  "Kolasib":"KO",
  "Lawngtlai":"LA",
  "Lunglei":"LU",
  "Mamit":"MA",
  "Saiha":"SA",
  "Saitual":"ST",
  "Serchhip":"SE",

// Nagaland (NL) - 12
  "Dimapur":"DI",
  "Kiphire":"KI",
  "Kohima":"KO",
  "Longleng":"LOMK",
  "Mokokchung":"MK",
  "Mon":"MN",
  "Noklak":"NK",
  "Peren":"PE",
  "Phek":"PH",
  "Tuensang":"TU",
  "Wokha":"WO",
  "Zunheboto":"ZU",

// Odisha (OR) - 30
  "Angul":"AN",
  "Boudh":"BD",
  "Bhadrak":"BH",
  "Balangir":"BL",
  "Bargarh":"BR",
  "Balasore":"BW",
  "Cuttack":"CU",
  "Debagarh":"DE",
  "Dhenkanal":"DH",
  "Ganjam":"GN",
  "Gajapati":"GP",
  "Jharsuguda":"JH",
  "Jajpur":"JP",
  "Jagatsinghpur":"JS",
  "Khordha":"KH",
  "Kendujhar":"KJ",
  "Kalahandi":"KL",
  "Kandhamal":"KN",
  "Koraput":"KO",
  "Kendrapara":"KP",
  "Malkangiri":"ML",
  "Mayurbhanj":"MY",
  "Nabarangpur":"NB",
  "Nuapada":"NU",
  "Nayagarh":"NY",
  "Puri":"PU",
  "Rayagada":"RA",
  "Sambalpur":"SA",
  "Subarnapur":"SO",
  "Sundargarh":"SU",

// Puducherry (PY) - 4
  "Karaikal":"KA",
  "Mahé":"MA",
  "Pondicherry":"PO",
  "Yanam":"YA",

// Punjab (PB) - 22
  "Amritsar":"AM",
  "Barnala":"BNL",
  "Bathinda":"BA",
  "Firozpur":"FI",
  "Faridkot":"FR",
  "Fatehgarh Sahib":"FT",
  "Fazilka":"FA",
  "Gurdaspur":"GU",
  "Hoshiarpur":"HO",
  "Jalandhar":"JA",
  "Kapurthala":"KA",
  "Ludhiana":"LU",
  "Mansa":"MA",
  "Moga":"MO",
  "Sri Muktsar Sahib":"MU",
  "Pathankot":"PA",
  "Patiala":"PAA",
  "Rupnagar":"RU",
  "Sahibzada Ajit Singh Nagar":"SAS",
  "Sangrur":"SA",
  "Shahid Bhagat Singh Nagar":"PB",
  "Tarn Taran":"TT",

// Rajasthan (RJ) - 33
  "Ajmer":"AJ",
  "Alwar":"AL",
  "Bikaner":"BI",
  "Barmer":"BM",
  "Banswara":"BN",
  "Bharatpur":"BP",
  "Baran":"BR",
  "Bundi":"BU",
  "Bhilwara":"BW",
  "Churu":"CR",
  "Chittorgarh":"CT",
  "Dausa":"DA",
  "Dholpur":"DH",
  "Dungarpur":"DU",
  "Ganganagar":"GA",
  "Hanumangarh":"HA",
  "Jhunjhunu":"JJ",
  "Jalore":"JL",
  "Jodhpur":"JO",
  "Jaipur":"JP",
  "Jaisalmer":"JS",
  "Jhalawar":"JW",
  "Karauli":"KA",
  "Kota":"KO",
  "Nagaur":"NA",
  "Pali":"PA",
  "Pratapgarh":"PG",
  "Rajsamand":"RA",
  "Sikar":"SK",
  "Sawai Madhopur":"SM",
  "Sirohi":"SR",
  "Tonk":"TO",
  "Udaipur":"UD",

// Sikkim (SK) - 4
  "East Sikkim":"ES",
  "North Sikkim":"NS",
  "South Sikkim":"SS",
  "West Sikkim":"WS",

// Tamil Nadu (TN) - 38
  "Ariyalur":"AY",
  "Chengalpattu":"CGL",
  "Chennai":"CH",
  "Coimbatore":"CO",
  "Cuddalore":"CU",
  "Dharmapuri":"DH",
  "Dindigul":"DI",
  "Erode":"ER",
  "Kallakurichi":"KL",
  "Kanchipuram":"KC",
  "Kanyakumari":"KK",
  "Karur":"KA",
  "Krishnagiri":"KR",
  "Madurai":"MDU",
  "Mayiladuthurai":"",
  "Nagapattinam":"NG",
  "Nilgiris":"NI",
  "Namakkal":"NM",
  "Perambalur":"PE",
  "Pudukkottai":"PU",
  "Ramanathapuram":"RA",
  "Ranipet":"RN",
  "Salem":"SA",
  "Sivaganga":"SI",
  "Tenkasi":"TS",
  "Tirupur":"TP",
  "Tiruchirappalli":"TC",
  "Theni":"TH",
  "Tirunelveli":"TI",
  "Thanjavur":"TJ",
  "Thoothukudi":"TK",
  "Tirupattur":"TP",
  "Tiruvallur":"TL",
  "Tiruvarur":"TR",
  "Tiruvannamalai":"TV",
  "Vellore":"VE",
  "Viluppuram":"VL",
  "Virudhunagar":"VR",

// Telangana (TG) - 33
  "Adilabad":"AD",
  "Komaram Bheem":"",
  "Bhadradri Kothagudem":"",
  "Hyderabad":"HY",
  "Jagtial":"",
  "Jangaon":"",
  "Jayashankar Bhupalpally":"",
  "Jogulamba Gadwal":"",
  "Kamareddy":"",
  "Karimnagar":"KA",
  "Khammam":"KH",
  "Mahabubabad":"",
  "Mahbubnagar":"MA",
  "Mancherial":"",
  "Medak":"ME",
  "Medchal-Malkajgiri":"",
  "Mulugu":"",
  "Nalgonda":"NA",
  "Narayanpet":"",
  "Nagarkurnool":"",
  "Nirmal":"",
  "Nizamabad":"NI",
  "Peddapalli":"",
  "Rajanna Sircilla":"",
  "Ranga Reddy":"RA",
  "SangaReddy":"",
  "Siddipet":"",
  "Suryapet":"",
  "Vikarabad":"",
  "Wanaparthy":"",
  "Warangal Urban":"WL",
  "Warangal Rural":"",
  "Yadadri Bhuvanagiri":"",

// Tripura (TR) - 8
  "Dhalai":"DH",
  "Gomati":"GM",
  "Khowai":"KH",
  "North Tripura":"NT",
  "Sepahijala":"SP",
  "South Tripura":"ST",
  "Unokoti":"UK",
  "West Tripura":"WT",

// Uttar Pradesh (UP) - 75
  "Agra":"AG",
  "Aligarh":"AL",
  "Prayagraj":"AH",
  "Ambedkar Nagar":"AN",
  "Amethi":"AM",
  "Amroha":"JP",
  "Auraiya":"AU",
  "Azamgarh":"AZ",
  "Bagpat":"BG",
  "Bahraich":"BH",
  "Ballia":"BL",
//  "Balrampur":"BP",
  "Banda":"BN",
  "Barabanki":"BB",
  "Bareilly":"BR",
  "Basti":"BS",
  "Bhadohi":"BH",
  "Bijnor":"BI",
  "Budaun":"BD",
  "Bulandshahr":"BU",
  "Chandauli":"CD",
  "Chitrakoot":"CT",
  "Deoria":"DE",
  "Etah":"ET",
  "Etawah":"EW",
  "Ayodhya":"FZ",
  "Farrukhabad":"FR",
  "Fatehpur":"FT",
  "Firozabad":"FI",
  "Gautam Buddh Nagar":"GB",
  "Ghaziabad":"GZ",
  "Ghazipur":"GP",
  "Gonda":"GN",
  "Gorakhpur":"GR",
//  "Hamirpur":"HM",
  "Hapur":"PN",
  "Hardoi":"HR",
  "Hathras":"HT",
  "Jalaun":"JL",
  "Jaunpur":"JU",
  "Jhansi":"JH",
  "Kannauj":"KJ",
  "Kanpur Dehat":"KD",
  "Kanpur Nagar":"KN",
  "Kasganj":"KR",
  "Kaushambi":"KS",
  "Kushinagar":"KU",
  "Lakhimpur Kheri":"LK",
  "Lalitpur":"LA",
  "Lucknow":"LU",
  "Maharajganj":"MG",
  "Mahoba":"MH",
  "Mainpuri":"MP",
  "Mathura":"MT",
  "Mau":"MB",
  "Meerut":"ME",
  "Mirzapur":"MI",
  "Moradabad":"MO",
  "Muzaffarnagar":"MU",
  "Pilibhit":"PI",
//  "Pratapgarh":"PR",
  "Raebareli":"RB",
  "Rampur":"RA",
  "Saharanpur":"SA",
  "Sambhal":"SM",
  "Sant Kabir Nagar":"SK",
  "Shahjahanpur":"SJ",
  "Shamli":"SH",
  "Shravasti":"SV",
  "Siddharthnagar":"SN",
  "Sitapur":"SI",
  "Sonbhadra":"SO",
  "Sultanpur":"SU",
  "Unnao":"UN",
  "Varanasi":"VA",

// Uttarakhand (UT) - 13
  "Almora":"AL",
  "Bageshwar":"BA",
  "Chamoli":"CL",
  "Champawat":"CP",
  "Dehradun":"DD",
  "Haridwar":"HA",
  "Nainital":"NA",
  "Pauri Garhwal":"PG",
  "Pithoragarh":"PI",
  "Rudraprayag":"RP",
  "Tehri Garhwal":"TG",
  "Udham Singh Nagar":"US",
  "Uttarkashi":"UT",


// West Bengal (WB) - 23
  "Alipurduar":"AD",
  "Bankura":"BN",
  "Paschim Bardhaman":"BR",
  "Purba Bardhaman":"BRR",
  "Birbhum":"BI",
  "Cooch Behar":"KB",
  "Dakshin Dinajpur":"DD",
  "Darjeeling":"DA",
  "Hooghly":"HG",
  "Howrah":"HR",
  "Jalpaiguri":"JA",
  "Jhargram":"JH",
  "Kalimpong":"KA",
  "Kolkata":"KO",
  "Maldah":"MA",
  "Murshidabad":"MSD",
  "Nadia":"NA",
  "North 24 Parganas":"PN",
  "Paschim Medinipur":"PM",
  "Purba Medinipur":"PR",
  "Purulia":"PU",
  "South 24 Parganas":"PS",
  "Uttar Dinajpur":"UD"
};