import 'package:flutter/cupertino.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:naya/localization/localizations_constants.dart';
import 'package:naya/aboutNG/contactus.dart';
import 'package:naya/widgets/ng_drawer.dart';
import 'package:naya/widgets/ng_widgets.dart';
import 'package:url_launcher/url_launcher.dart';


class TermsAndConditions extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        return Navigator.canPop(context);
      },child:Scaffold(
      appBar: ngAppBar(getTranslated(context,'terms_and_conditions'),context),
      drawer: NGDrawer(),
      body: Padding(
        padding: EdgeInsets.fromLTRB(30.0, 10.0, 20.0, 20.0),
        child: ListView(
          children: <Widget>[
            
            Text(getTranslated(context, "terms_text1") ,
              textAlign: TextAlign.center,
              style: ngBoldTextStyle(),
            ),

            SizedBox(height: 10.0,),
            Text(getTranslated(context, "terms_text2") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text3") ,
              style: ngTextStyle(),
            ),
            
            Text.rich(
              TextSpan(
                children: [
                  TextSpan(
                    text: getTranslated(context, "terms_text4") ,
                    style: ngTextStyle()
                  ),

                  TextSpan(
                    text: getTranslated(context, "terms_text5") ,
                    style: ngHyperLinkTextStyle(),
                    recognizer: TapGestureRecognizer()
                      ..onTap = () async {
                        launch("https://www.nayagaadi.com");
                      },
                  ),

                  TextSpan(
                    text: getTranslated(context, "terms_text6") ,
                    style: ngTextStyle(),
                  ),
                ]
              )
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text7") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text8") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text9") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text10") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text11") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text12") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text13") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text14") ,
              style: ngTextStyle(),
            ),

            // Membership Eligibility
            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text15") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text16") ,
              style: ngTextStyle(),
            ),

            // YOUR ACCOUNT AND REGISTRATION OBLIGATIONS
            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text17") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text18") ,
              style: ngTextStyle(),
            ),

            // CONTENT ON NayaGaadi COMMUNITY
            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text19") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text20") ,
              style: ngTextStyle(),
            ),


            Text(getTranslated(context, "terms_text21") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text22") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text23") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text24") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text25") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text26") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text27") ,
              style: ngTextStyle(),
            ),

            SizedBox(height: 10,),

            // LICENSE FOR THE CONTENT POSTED ON THE WEBSITE
            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text28") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10,),


            Text(getTranslated(context, "terms_text29") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text51") ,
            style: ngBoldTextStyle(),),
            SizedBox(height: 10,),

            Text(getTranslated(context, "terms_text30") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text31") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10,),
            Text(getTranslated(context, "terms_text32") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text33") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10,),
            Text(getTranslated(context, "terms_text34") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text35") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10,),
            Text(getTranslated(context, "terms_text36") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text37") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text38") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text39") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text40") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text41") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text42") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text43") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text44") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text45") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text46") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text47") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text48") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text49") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text50") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text52") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text53") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text54") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text55") ,
              style: ngTextStyle(),
            ),


            Opacity(
              opacity: 0.5,
              child: Text(getTranslated(context, "terms_text56") ,style: ngBoldTextStyle(),),
            ),
            Text(getTranslated(context, "terms_text57") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child: Text(getTranslated(context, "terms_text58") ,style: ngBoldTextStyle(),),
            ),

            Text(getTranslated(context, "terms_text59") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text60") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text61") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text62") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text63") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text64") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text65") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text66") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text67") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text68") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text69") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text70") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text71") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text72") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text73") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text74") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text75") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text76") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text77") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text78") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text79") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text80") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text81") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text82") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text83") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text84") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text85") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text86") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text87") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text88") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text89") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text90") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text91") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text92") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text93") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text94") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text95") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text96") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text97") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text98") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text99") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text100") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text101") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child: Text(getTranslated(context, "terms_text102") ),
            ),
            
            Text(getTranslated(context, "terms_text103") ,style: ngBoldTextStyle(),),

            Text(getTranslated(context, "terms_text104") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text105") ,style: ngBoldTextStyle(),),

            Text(getTranslated(context, "terms_text106") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text107") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text108") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context, "terms_text109") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text110") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text111") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text112") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text113") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text114") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text115") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text116") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text117") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text118") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),
            Text(getTranslated(context, "terms_text119") ,
              style: ngTextStyle(),
            ),
            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text120") ,
                style: ngBoldTextStyle(),
              ),
            ),
            Text(getTranslated(context, "terms_text121") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text122") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text123") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text124") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text125") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text126") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text127") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text128") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text129") ,
              style: ngTextStyle(),
            ),
            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text130") ,
                style: ngBoldTextStyle(),
              ),
            ),
            Text(getTranslated(context, "terms_text131") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text132") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text133") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text134") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text135") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text136") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text137") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text138") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text139") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text140") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text141") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text142") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text143") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text144") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text145") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text146") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text147") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text148") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text149") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text150") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text151") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text152") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text153") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),
            Text(getTranslated(context, "terms_text154") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text155") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),
            Text(getTranslated(context, "terms_text156") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text157") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text158") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text159") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text160") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text161") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text162") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text163") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text164") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text165") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text166") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text167") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text168") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text169") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text170") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text171") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text172") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text173") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text174") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text175") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text176") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text177") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text178") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text179") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text180") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text181") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text182") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text183") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text184") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text185") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text186") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text187") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text188") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text189") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text190") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text191") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text192") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text193") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text194") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text195") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text196") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text197") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text198") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text199") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text200") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text201") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text202") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text203") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text204") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text205") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text206") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text207") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text208") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text209") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text210") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text211") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text212") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text213") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text214") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text215") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text216") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text217") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text218") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text219") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text220") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text221") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text222") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text223") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text224") ,
                style: ngBoldTextStyle(),
              ),
            ),

            Text(getTranslated(context, "terms_text225") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text226") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text227") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text228") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text229") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text230") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text231") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text232") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context, "terms_text233") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text234") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child: Text(getTranslated(context, "terms_text235") ,
                style: ngTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text236") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child: Text(getTranslated(context, "terms_text237") ,
                style: ngTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text238") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text239") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text240") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text241") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text242") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child: Text(getTranslated(context, "terms_text243") ,
                style: ngTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text244") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text245") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text246") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text247") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text248") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text249") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text250") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text251") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text252") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text253") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text254") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text255") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text256") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text257") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text258") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text259") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text260") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text261") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text262") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text263") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text264") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text265") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text266") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text267") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text268") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text269") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text270") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text271") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text272") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context, "terms_text273") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text274") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text275") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text276") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text277") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text278") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text279") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text280") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text281") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text282") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text283") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text284") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text285") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text286") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text287") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text288") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text289") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text290") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text291") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text292") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text293") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text294") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text295") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text296") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text297") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text298") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text299") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text300") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text301") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text302") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text303") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text304") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text305") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text306") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text307") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text308") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text309") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text310") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text311") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text312") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text313") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text314") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text315") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text316") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text317") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text318") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text319") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text320") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text321") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text322") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text323") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text324") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text325") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text326") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text327") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text328") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text329") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text330") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text331") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text332") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text333") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text334") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text335") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text336") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text337") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text338") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text339") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text340") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text341") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text342") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text343") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text344") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text345") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text346") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text347") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text348") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text349") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text350") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text351") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text352") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text353") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text354") ,
              style: ngTextStyle(),
            ),

            Opacity(
              opacity: 0.5,
              child:Text(getTranslated(context, "terms_text355") ,
                style: ngBoldTextStyle(),
              ),
            ),
            SizedBox(height: 10.0,),

            Text(getTranslated(context, "terms_text356") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text357") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text358") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text359") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text360") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text361") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text362") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text363") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text364") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text365") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text366") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text367") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text368") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text369") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text370") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text371") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text372") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text373") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text374") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text375") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text376") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text377") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text378") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text379") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text380") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text381") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text382") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text383") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text384") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text385") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text386") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text387") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text388") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text389") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text390") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text391") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text392") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text393") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text394") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text395") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text396") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text397") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text398") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text399") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text400") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text401") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text402") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text403") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text404") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context, "terms_text405") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text406") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context, "terms_text407") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text408") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context, "terms_text409") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text410") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context, "terms_text411") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text412") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context, "terms_text413") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context, "terms_text414") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context, "terms_text415") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text416") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text417") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text418") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text419") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text420") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text421") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text422") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text423") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text424") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context, "terms_text425") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context, "terms_text426") ,
              style: ngBoldTextStyle(),
            ),
            Opacity(
              opacity: 0.5,
              child: Text(getTranslated(context, "terms_text427") ,
                style: ngTextStyle(),
              ),
            ),

            // Time
            Opacity(
              opacity: 0.5,
              child: Text.rich(
                TextSpan(
                  children: [
                    TextSpan(
                        text: getTranslated(context, "terms_text428") ,
                        style: ngBoldTextStyle()
                    ),
                    TextSpan(
                      text: getTranslated(context, "terms_text429") ,
                      style: ngTextStyle(),
                    ),
                  ],
                ),
              ),
            ),

            // email
            Opacity(
              opacity: 0.5,
              child: Text.rich(
                TextSpan(
                  children: [
                    TextSpan(
                        text: getTranslated(context, "terms_text430") ,
                        style: ngBoldTextStyle()
                    ),
                    TextSpan(
                      text: "nayagaadi@gmail.com" ,
                      style: ngTextStyle(),
                      recognizer: TapGestureRecognizer()
                        ..onTap = () async {
                          Services().mailUs();
                        },
                    ),
                  ],
                ),
              ),
            ),

            SizedBox(height: 30,),
          ],
        ),
      ),
    ));
  }
}