import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:naya/localization/localizations_constants.dart';
import 'package:naya/widgets/ng_drawer.dart';
import 'package:naya/widgets/ng_widgets.dart';
import 'package:url_launcher/url_launcher.dart';


class VisitorPolicy extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        return Navigator.canPop(context);
      },child:Scaffold(
      appBar: ngAppBar(getTranslated(context,'visitor_policy'),context),
      drawer: NGDrawer(),
      body: Padding(
        padding: EdgeInsets.fromLTRB(30.0, 10.0, 20.0, 20.0),
        child: ListView(
          children: <Widget>[
            Text(
              getTranslated(context,"visit_text01"),
              style: ngBoldTextStyle(),
            ),
            Text.rich(
              TextSpan(
                children: [
                  TextSpan(
                    text: getTranslated(context,"visit_text2"),
                    style: ngTextStyle(),
                  ),
                  TextSpan(
                    text: getTranslated(context,"visit_text3"),
                    style: ngHyperLinkTextStyle(),
                    recognizer: TapGestureRecognizer()
                      ..onTap = () async {
                        launch("https://www.nayagaadi.com");
                      },
                  ),
                  TextSpan(
                    text: getTranslated(context,"visit_text4"),
                    style: ngTextStyle(),
                  ),
                  TextSpan(
                    text: getTranslated(context,"visit_text5"),
                    style: ngTextStyle(),
                  ),
                  TextSpan(
                    text: getTranslated(context,"visit_text3"),
                    style: ngHyperLinkTextStyle(),
                    recognizer: TapGestureRecognizer()
                      ..onTap = () async {
                        launch("https://www.nayagaadi.com");
                      },
                  ),
                  TextSpan(
                    text: getTranslated(context,"visit_text6"),
                    style: ngTextStyle(),
                  ),
                  TextSpan(
                    text: getTranslated(context,"visit_text7") ,
                    style: ngTextStyle(),
                  ),
                ]
              ),
            ),
            Text(getTranslated(context,"visit_text8") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text9") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text10") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text11") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text12") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text13") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text14") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text15") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text16") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text17") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text18") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context,"visit_text19") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text20") ,
              style: ngBoldTextStyle(),
            ),

            Text(getTranslated(context,"visit_text21") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text22") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text23")  ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text24") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text25") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text26") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text27") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text28") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text29") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text30") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text31") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text32") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text33") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text34") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text35") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text36") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text37") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text38") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text39") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text40") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text41") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text42") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text43") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text44") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text45") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text46") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text47") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text48") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text49") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text50") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text51") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text52") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text53") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text54") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text55") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text56") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text57") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text58") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text59") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text60") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text61") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text62") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text63") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text64") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text65") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text66") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text67") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text68") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text69") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text70") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text71") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text72") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text73") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text74") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text75") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text76") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text77") ,
              style: ngTextStyle(),
            ),

            Text(getTranslated(context,"visit_text78") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text79") ,
              style: ngTextStyle(),
            ),
            Text(getTranslated(context,"visit_text80") ,
              style: ngBoldTextStyle(),
            ),
            Text(getTranslated(context,"visit_text81") ,
              style: ngTextStyle(),
            ),

            SizedBox(height: 10,),
          ],
        ),
      ),
    ));
  }
}